version: '3'
services:

  mongo_db:
    container_name: db_container
    image: mongo
    ports:
      - "27017:27017" # Map container port 27017 to host port 27017
    volumes:
      - mongo-data:/data/db # Optional volume to persist data

  app:
    container_name: myapp
    image: paulboon/myapp
    ports:
      - "80:8000"
    environment:
      PORT: 8000
      MONGODB_HOST: mongodb://mongo_db:27017
    depends_on:
      - mongo_db # Make sure app starts after mongodb


volumes:
  mongo-data: